<?php

return [
    [
        "title" => "Margarita",
        "description" => "Una margarita classica e rinfrescante con tequila, succo di lime e triple sec.",
        "thumb" => "https://example.com/margarita.jpg",
        "ingredients" => "Tequila, Triple sec, Succo di lime, Sale",
        "instructions" => "Strofina il bordo del bicchiere con una fetta di lime per far aderire il sale. Agita gli altri ingredienti con ghiaccio e versa delicatamente nel bicchiere.",
    ],
    [
        "title" => "Mojito",
        "description" => "Un cocktail cubano classico con rum, menta fresca e succo di lime.",
        "thumb" => "https://example.com/mojito.jpg",
        "ingredients" => "Rum bianco, Zucchero, Succo di lime, Acqua gassata, Menta",
        "instructions" => "Mescola le foglie di menta con zucchero e succo di lime. Aggiungi un po' di acqua gassata e riempi il bicchiere di ghiaccio. Versa il rum sul ghiaccio e riempi il bicchiere di acqua gassata. Decora con foglie di menta e una fetta di lime.",
    ],
    [
        "title" => "Old Fashioned",
        "description" => "Un cocktail classico con whisky, zucchero e angostura.",
        "thumb" => "https://example.com/old_fashioned.jpg",
        "ingredients" => "Whisky, Zucchero, Angostura, Acqua",
        "instructions" => "Metti una zolletta di zucchero in un bicchiere e saturala con angostura. Aggiungi un po' d'acqua e mescola finché non si scioglie. Riempi il bicchiere con cubetti di ghiaccio e aggiungi il whisky. Decora con una fetta d'arancia e una ciliegia.",
    ],
    [
        "title" => "Piña Colada",
        "description" => "Una miscela dolce e tropicale di rum, crema di cocco e succo di ananas.",
        "thumb" => "https://example.com/pina_colada.jpg",
        "ingredients" => "Rum bianco, Crema di cocco, Succo di ananas",
        "instructions" => "Mescola tutti gli ingredienti con ghiaccio in un frullatore fino ad ottenere una consistenza liscia. Servi in un bicchiere alto e decora con una fetta di ananas e una ciliegia.",
    ],
    [
        "title" => "Cosmopolitan",
        "description" => "Un cocktail elegante con vodka, triple sec, succo di mirtillo e succo di lime.",
        "thumb" => "https://example.com/cosmopolitan.jpg",
        "ingredients" => "Vodka, Triple sec, Succo di mirtillo, Succo di lime",
        "instructions" => "Agita tutti gli ingredienti con ghiaccio in uno shaker e filtra in una coppa da cocktail. Decora con una fetta di lime.",
    ],
    [
        "title" => "Mai Tai",
        "description" => "Un cocktail tiki classico con rum, curaçao all'arancia, sciroppo di orzata e succo di lime.",
        "thumb" => "https://example.com/mai_tai.jpg",
        "ingredients" => "Rum bianco, Rum scuro, Curaçao all'arancia, Sciroppo di orzata, Succo di lime",
        "instructions" => "Agita tutti gli ingredienti con ghiaccio e filtra in un bicchiere pieno di ghiaccio tritato. Decora con una fetta di lime e un rametto di menta.",
    ],
    [
        "title" => "Daiquiri",
        "description" => "Un cocktail semplice e rinfrescante con rum, succo di lime e zucchero.",
        "thumb" => "https://example.com/daiquiri.jpg",
        "ingredients" => "Rum bianco, Succo di lime, Zucchero",
        "instructions" => "Agita tutti gli ingredienti con ghiaccio e filtra in una coppa da cocktail. Decora con una fetta di lime.",
    ],
    [
        "title" => "Manhattan",
        "description" => "Un cocktail classico e sofisticato con whisky, vermut dolce e angostura.",
        "thumb" => "https://example.com/manhattan.jpg",
        "ingredients" => "Whisky, Vermut dolce, Angostura",
        "instructions" => "Mescola tutti gli ingredienti con ghiaccio e filtra in una coppa da cocktail. Decora con una ciliegia.",
    ],
    [
        "title" => "Negroni",
        "description" => "Un cocktail italiano classico con gin, vermut dolce e Campari.",
        "thumb" => "https://example.com/negroni.jpg",
        "ingredients" => "Gin, Vermut dolce, Campari",
        "instructions" => "Mescola tutti gli ingredienti con ghiaccio e filtra in un bicchiere basso con ghiaccio. Decora con una fetta d'arancia.",
    ],
    [
        "title" => "Whiskey Sour",
        "description" => "Un cocktail acido e dolce con whisky, succo di limone e sciroppo di zucchero.",
        "thumb" => "https://example.com/whiskey_sour.jpg",
        "ingredients" => "Whisky, Succo di limone, Sciroppo di zucchero",
        "instructions" => "Agita tutti gli ingredienti con ghiaccio e filtra in un bicchiere basso con ghiaccio. Decora con una fetta di limone e una ciliegia.",
    ],
    [
        "title" => "Martini",
        "description" => "Un cocktail elegante e secco con gin e vermut secco.",
        "thumb" => "https://example.com/martini.jpg",
        "ingredients" => "Gin, Vermut secco",
        "instructions" => "Mescola tutti gli ingredienti con ghiaccio e filtra in una coppa da cocktail. Decora con un'oliva o una fetta di limone.",
    ],
    [
        "title" => "Bloody Mary",
        "description" => "Un cocktail salato e piccante con vodka, succo di pomodoro e condimenti.",
        "thumb" => "https://example.com/bloody_mary.jpg",
        "ingredients" => "Vodka, Succo di pomodoro, Salsa Worcestershire, Salsa piccante, Succo di limone, Sale, Pepe",
        "instructions" => "Mescola tutti gli ingredienti con ghiaccio e servi in un bicchiere alto. Decora con un gambo di sedano e una fetta di limone.",
    ],
    [
        "title" => "Mint Julep",
        "description" => "Un cocktail rinfrescante del sud degli Stati Uniti con bourbon, menta e zucchero.",
        "thumb" => "https://example.com/mint_julep.jpg",
        "ingredients" => "Bourbon, Menta, Zucchero, Acqua",
        "instructions" => "Mescola le foglie di menta con zucchero e un po' d'acqua in un bicchiere. Riempi il bicchiere di ghiaccio tritato e aggiungi bourbon. Decora con un rametto di menta.",
    ],
    [
        "title" => "Caipirinha",
        "description" => "Un cocktail brasiliano classico con cachaça, lime e zucchero.",
        "thumb" => "https://example.com/caipirinha.jpg",
        "ingredients" => "Cachaça, Lime, Zucchero",
        "instructions" => "Mescola le fette di lime con zucchero in un bicchiere. Riempi il bicchiere di ghiaccio e aggiungi cachaça. Mescola bene e servi.",
    ],
    [
        "title" => "Pisco Sour",
        "description" => "Un cocktail peruviano classico con pisco, succo di limone, sciroppo di zucchero e albume.",
        "thumb" => "https://example.com/pisco_sour.jpg",
        "ingredients" => "Pisco, Succo di limone, Sciroppo di zucchero, Albume, Angostura",
        "instructions" => "Agita tutti gli ingredienti con ghiaccio e filtra in una coppa da cocktail. Decora con qualche goccia di angostura.",
    ],
];
